
-- +migrate Up

CREATE TABLE whale (
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
 address TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL UNIQUE,
 added DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_sent DATE DEFAULT CURRENT_TIMESTAMP,
 last_received DATE DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE whale;
